---
name: Test workflow

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  job1:
    uses: "./.github/workflows/subworkflow.yml"

  job2:
    needs: job1
    if: ${{!cancelled() && needs.job1.outputs.rc == 'failure' }}
    #if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: hello_world
        run: |
          echo "hello world 2" 

...
