---
name: Test workflow

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Hello world
        id: hello_world
        # continue-on-error: true overrides the exit code, so this doesn't work
        #run: echo "hello world"
        run: exit 1

    outputs:
      rc: ${{ steps.hello_world.conclusion }}

  job2:
    needs: job1
    if: ${{!cancelled() && needs.job1.outputs.rc == 'failure' }}
    #if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: hello_world
        run: |
          echo "hello world 2" 

...
