---
name: Test workflow

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: hello_world
        #run: echo "hello world"
        run: exit 1

    outputs:
      rc: ${{ steps.hello_world.conclusion }}

  job2:
    needs: job1
    if: ${{!cancelled() && needs.job1.outputs.rc == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: hello_world
        run: echo "hello world 2.  Conclusion\:" ${{ needs.job1.outputs.rc }}

...
